name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write env from repository secrets
        run: |
          cat > .env << EOF
          TOKEN=${{ secrets.TOKEN }}
          MAIN_GROUP_ID=${{ secrets.MAIN_GROUP_ID }}
          EDIT_MESSAGE_ID=${{ secrets.EDIT_MESSAGE_ID }}
          ADD_CALENDAR_LINK=${{ secrets.ADD_CALENDAR_LINK }}
          EOF

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Files using Rsync
        run: |
          rsync -avz --exclude='.git' -e "ssh -p ${{ secrets.SSH_PORT }}" $GITHUB_WORKSPACE/ ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.PROJECT_PATH }}

      - name: Restart bot
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} \
            "cd ${{ secrets.PROJECT_PATH }} && docker compose up -d --build"
